sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.7.1

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-ce
    - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

language: php
php:
- 7.2

script:
    - composer install
    - ./vendor/bin/phpunit src/OpenCATS/Tests/UnitTests
    - cd docker/; docker-compose -f docker-compose-test.yml up -d
    - docker-compose -f docker-compose-test.yml exec php /var/www/public/test/runAllTests.sh
    - env
    - echo $TRAVIS_TAG
    - cd ..; ./ci/package-code.sh 

deploy:
  provider: releases
  api_key:
    secure: Srgq/VW4yoYg0yWq/llOix47MAe2EKccqxfdukxrm6fePKRRv6bVBQXH/0hhrTTn4Q6xrmVycqC36SD9/JVL684xNYBESlT4V3DpZ6vxPYeNzU2GjtoMBqGCOgjZvxpq5AGIf7gXZ9GdM4+xikBPthspCcUorg8hkLgaOQ5PPlI0dC7cdFPjQweoxAqDe6VwQ31J1MiO+DPI+69GHb/KukHkS/sjhZTMZoO0shfw5dhv0TSuaeaPzWYw1+g6sNdgNurNbi4bPEEpofUdfA+WaWw7oapsO7ZW4qTqKxsrsrCf1ZgTnynm2Kow5D7oFVqRkt/kpoQ/UzwZUalzm8JrVeYPbQ2j7mYxOh3TcTYn24NSm8xuDgF8ZaG3BxoWCLQSA8pdJZRI7QbWrDdFA93ZD1EWRW0amL3rOGLED61K0ZFhulUBy1bKyjAnT2T6FPsKk4hOwFDo1nojzemQnl6PfPT6Lsuvk5FotevsemBUQl+xx7UQsxhDM3kw3/IheE/abOYmIK+qRKdcH5J04m+dadXKZBa+h/Jsd5AdC7Yp3Si74IhJFceyvQIx7GkkG4fo/0Y34mCAXuwEN7acB7RbNU8DVyzfUtpWSPwkw2iDTJshDsV1RN94Xzt+k/GvLAvAOttozkhruYV563+MEYizBRN+96jaF/35dZYd+X3UwBA=
    secure: TRb8uQSt22NNKczLj6QvnBAjd953tb3bpQIdiltcVl7JhZ6YBWnylwEAMt3EryxD1ZqWsCS89F00VR/lo9N+iSZJfuN8xQGh76CS6MTG46DqFcgIbjkAjK3EFxqZamLfQKeQytfmIvsWJ3dDcwSjSrvvcAoI/Lklzpq2NoVfHj/6M+HX7q41tiucRfajrxC47bFgsOkljOfWuUYGteQ/hZOGeyZ5lNUfZDzSTPyaVamf6nPmHGi9Tbjks+YL6rvZ32MAkZpY4FQAFKhXELTjM6FSYW9V7n8Vq4ufaaN93UYXb3x5Yx1+ZBmAdbp3kQCt0gwe4aQtuT0kRft7rkD0Tg7Xp2ao2KyN1gzZN2ptHsXdNB9Y4yRv7pIsNPYXSQyi1ofPMWRO+zIjl1Je0kQ981YfWqu7RcqwPIQ6PVE34kT4hDMuRmzOqgrtnO07ZgozdhUCAK33aBIcGq4ZW7RXgvaNk0BmvZAP5oeM4wj/OUKpC7yw14fTOdGxETvP4E0zYc9TnfAxVhNHRGhGqWtLZshZ1/8apcjDO1eAN6x1Wa/tESWOzqADra+7ga09SSR8Agc1sVW9gW0UVqawNE83+cwzL5fO/lgIkIRVlZtsPMAYkzHMu9IeA0f1aV8yKML3znZuh8c6BKw4nZx6K/GhCqCqfNefNReaeeMMXXg99HI=

file:
     - $TRAVIS_BUILD_DIR/opencats-$TRAVIS_TAG-full.tar.gz
     - $TRAVIS_BUILD_DIR/opencats-$TRAVIS_TAG-full.zip
  skip_cleanup: true
  on:
    tags: true

